name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with GCP
      env:
        GCP_KEY: ${{ secrets.GCP_KEY }}
      run: |
        echo "${GCP_KEY}" | base64 --decode > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    # Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}"
        docker build -t "$IMAGE_NAME" .
        gcloud auth configure-docker --quiet
        docker push "$IMAGE_NAME"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with GCP
      env:
        GCP_KEY: ${{ secrets.GCP_KEY }}
      run: |
        echo "${GCP_KEY}" | base64 --decode > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE }}"
        gcloud run deploy ${{ secrets.GCP_SERVICE }} \
          --image "$IMAGE_NAME" \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated